version: '3.9'

services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 123qwe
    ports:
      - "1433:1433"
    container_name: sql_server